import type { Metadata } from "next";
import { Roboto, Inter } from "next/font/google";
import "tw-elements-react/dist/css/tw-elements-react.min.css";

import "./globals.css";
import Navbar from "@/components/Navigation/Navbar";

import ReactQueryProvider from "@/providers/ReactQueryProvider";
const roboto = Roboto({ weight: "400", subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <header>
            <Navbar />
          </header>
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
