version: "3"

volumes:
  postgres_data:

networks:
  arg-network:

services:
  express-server:
    container_name: node-server
    image: arg-express-server
    build:
      context: ./
      dockerfile: Dockerfile
      target: deployment
    networks:
      - arg-network
    volumes:
      - ./src:/usr/app/src
    ports:
      - 80:8000
    env_file:
      - .env

  postgres-server:
    container_name: postgres-db
    image: postgres:15.5-alpine3.19
    networks:
      - arg-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: arg_user
      POSTGRES_PASSWORD: QX!p6?0v485U
      POSTGRES_DB: arg
    ports:
      - 5432:5432
